env:
  AWS_DEFAULT_REGION: ap-southeast-2

steps:

  - command: ls -l
    label: ':hammer: Check docker'
    env:
      ENVIRONMENT: dev
    agents:
      queue: pact-dev

  - command: /workdir/scripts/build-site.sh
    label: ':hammer: Doc Site - Build'
    env:
      ENVIRONMENT: dev
    agents:
      queue: pact-dev
    plugins:
      - docker#v3.2.0:
          image: "{ECR}.dkr.ecr.ap-southeast-2.amazonaws.com/build-container-yarn:latest"
          propagate-environment: true
          user: node
          always-pull: true
