AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  HostedZone:
    Description: HostedZone to attach the domain to
    Type: String
  HostedZoneName:
    Description: HostedZoneName to attach the domain to
    Type: String
  HostName:
    Description: Domain name to host the website on
    Type: String
    Default: docs
  Environment:
    Description: One of 'dev' or 'prod'
    Type: String
  WebsiteCert:
    Description: ARN of the website certificate
    Type: String

Resources:
  WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
          AccessControl: PublicRead
          BucketName: !Ref HostName
          WebsiteConfiguration:
            ErrorDocument: 404.html
            IndexDocument: index.html

  WebsiteDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
          DistributionConfig:
              Origins:
                  - Id: only-origin
                    DomainName: !Sub "${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com"
                    CustomOriginConfig:
                      HTTPPort: '80'
                      HTTPSPort: '443'
                      OriginProtocolPolicy: http-only
              CustomErrorResponses:
                - ErrorCachingMinTTL: 300
                  ErrorCode: 404
                  ResponseCode: 404
                  ResponsePagePath: error.html
              Enabled: 'true'
              DefaultCacheBehavior:
                  ForwardedValues:
                      QueryString: 'true'
                  TargetOriginId: only-origin
                  ViewerProtocolPolicy: redirect-to-https
              DefaultRootObject: index.html
              Aliases:
                - !Sub ${HostName}.${HostedZoneName}
              ViewerCertificate:
                  AcmCertificateArn: !Ref WebsiteCert
                  SslSupportMethod: sni-only

  OriginRecord:
    Type: AWS::Route53::RecordSet
    Properties:
        AliasTarget:
          DNSName: !GetAtt WebsiteDistribution.DomainName
          HostedZoneId: Z2FDTNDATAQYW2
        HostedZoneId: !Ref 'HostedZone'
        Comment: DNS name for doco site.
        Name: !Sub ${HostName}.${HostedZoneName}
        Type: A

  AliasedRecord:
    Type: AWS::Route53::RecordSet
    Properties:
        AliasTarget:
          DNSName: !GetAtt WebsiteDistribution.DomainName
          HostedZoneId: Z2FDTNDATAQYW2
        HostedZoneId: !Ref 'HostedZone'
        Comment: DNS name for doco site.
        Name: !Sub ${HostName}.${Environment}.${HostedZoneName}
        Type: A

Outputs:
  WebsiteBucket:
    Description: Bucket that hosts the website
    Value: !Ref WebsiteBucket
