AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  HostedZone:
    Description: HostedZone to attach the domain to
    Type: String
  HostName:
    Description: Domain name to host the website on
    Type: String
    Default: docs
  WebsiteCert:
    Description: ARN of the website certificate
    Type: String

Resources:
  WebsiteBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
          BucketName: !Ref HostName
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          WebsiteConfiguration:
            ErrorDocument: 404.html
            IndexDocument: index.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt WebsiteDistributionIdentity.S3CanonicalUserId
            Resource:
              - !GetAtt WebsiteBucket.Arn
              - !Sub ${WebsiteBucket.Arn}/*

  WebsiteDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
          DistributionConfig:
              Origins:
                  - Id: only-origin
                    DomainName: !Sub "${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com"
                    S3OriginConfig:
                      OriginAccessIdentity: !Join
                        - ''
                        - - origin-access-identity/cloudfront/
                          - !Ref 'WebsiteDistributionIdentity'
              CustomErrorResponses:
                - ErrorCachingMinTTL: 300
                  ErrorCode: 404
                  ResponseCode: 404
                  ResponsePagePath: /index.html
              Enabled: true
              DefaultCacheBehavior:
                  ForwardedValues:
                      QueryString: true
                  TargetOriginId: only-origin
                  ViewerProtocolPolicy: redirect-to-https
              DefaultRootObject: index.html
              Aliases:
                - !Sub ${HostName}
              ViewerCertificate:
                  AcmCertificateArn: !Ref WebsiteCert
                  SslSupportMethod: sni-only

  WebsiteDistributionIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Allows CloudFront to reach the bucket

  OriginRecord:
    Type: AWS::Route53::RecordSet
    Properties:
        AliasTarget:
          DNSName: !GetAtt WebsiteDistribution.DomainName
          HostedZoneId: Z2FDTNDATAQYW2
        HostedZoneId: !Ref 'HostedZone'
        Comment: DNS name for doco site.
        Name: !Sub ${HostName}
        Type: A

Outputs:
  WebsiteBucket:
    Description: Bucket that hosts the website
    Value: !Ref WebsiteBucket
