name: Sync Pact docs

on:
  repository_dispatch:
    types:
      - pactflow-docs-updated
      - pactflow-cypress-example-updated
      - pactflow-example-consumer-dotnet-updated
      - pactflow-example-provider-dotnet-updated
      - pactflow-example-consumer-java-kafka-updated
      - pactflow-example-consumer-js-updated
      - pactflow-example-consumer-js-kafka-updated
      - pactflow-example-provider-java-kafka-updated
      - pactflow-example-consumer-java-soap-updated
      - pactflow-example-provider-java-soap-updated
      - pactflow-example-provider-java-spring-boot-updated
      - pactflow-example-consumer-java-junit-updated
      - pactflow-example-provider-js-updated
      - pactflow-example-consumer-python-updated
      - pactflow-example-provider-python-updated
      - pact-workshop-js-updated
      - pactflow-example-provider-js-sns-updated
      - pactflow-example-consumer-js-sns-updated
      - pactflow-example-provider-golang-updated
      - pactflow-example-consumer-golang-updated
      - pactflow-example-provider-dredd-updated
      - pactflow-example-provider-postman-updated
      - pactflow-example-provider-restassured-updated
      - pactflow-example-consumer-wiremock-updated
      - pactflow-example-bdc-consumer-dotnet-updated
      - pactflow-example-bdc-consumer-cypress-updated
      - pactflow-example-bdc-provider-dotnet-updated
      - pactflow-example-bdc-consumer-mountebank-updated
      - pactflow-example-bdc-consumer-dotnet-updated
      - pactflow-example-bdc-consumer-cypress-updated
      - pactflow-example-bdc-provider-dotnet-updated
      - pactflow-example-bdc-consumer-mountebank-updated
      - pactflow-example-consumer-msw-js-updated

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - run: gem install bundler -v 2.0.2 && bundle install --without test development

      - name: Sync example_consumer_cypress docs
        run: bundle exec scripts/sync/example_consumer_cypress.rb && echo 'COMMIT_MESSAGE="synced pactflow_consumer_cypress docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-cypress-example-updated'

      - name: Sync example_consumer_dotnet docs
        run: bundle exec scripts/sync/example_consumer_dotnet.rb && echo 'COMMIT_MESSAGE="synced example_consumer_dotnet docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-consumer-dotnet-updated'

      - name: Sync example_provider_dotnet docs
        run: bundle exec scripts/sync/example_provider_dotnet.rb && echo 'COMMIT_MESSAGE="synced example_provider_dotnet docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-provider-dotnet-updated'

      - name: Sync example_consumer_java_kafka docs
        run: bundle exec scripts/sync/example_consumer_java_kafka.rb && echo 'COMMIT_MESSAGE="synced example_consumer_java_kafka docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-consumer-java-kafka-updated'

      - name: Sync example_consumer_js docs
        run: bundle exec scripts/sync/example_consumer_js.rb && echo 'COMMIT_MESSAGE="synced example_consumer_js docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-consumer-js-updated'

      - name: Sync example_consumer_js_sns docs
        run: bundle exec scripts/sync/example_consumer_js_sns.rb && echo 'COMMIT_MESSAGE="synced example_consumer_js_kafka docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-consumer-js-kafka-updated'

      - name: Sync example_provider_java_kafka docs
        run: bundle exec scripts/sync/example_provider_java_kafka.rb && echo 'COMMIT_MESSAGE="synced example_provider_java_kafka docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-provider-java-kafka-updated'

      - name: Sync example_consumer_java_soap docs
        run: bundle exec scripts/sync/example_consumer_java_soap.rb && echo 'COMMIT_MESSAGE="synced example_consumer_java_kafka docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-consumer-java-soap-updated'

      - name: Sync example_provider_java_soap docs
        run: bundle exec scripts/sync/example_provider_java_soap.rb && echo 'COMMIT_MESSAGE="synced example_provider_js_kafka docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-provider-java-soap-updated'

      - name: Sync example_provider_java_spring_boot docs
        run: bundle exec scripts/sync/example_provider_java_spring_boot.rb && echo 'COMMIT_MESSAGE="synced example_provider_java_spring_boot docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-provider-java-spring-boot-updated'

      - name: Sync example_consumer_java_junit docs
        run: bundle exec scripts/sync/example_consumer_java_junit.rb && echo 'COMMIT_MESSAGE="synced example_consumer_java_junit docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-consumer-java-junit-updated'

      - name: Sync example_provider_js docs
        run: bundle exec scripts/sync/example_provider_js.rb && echo 'COMMIT_MESSAGE="synced example_provider_js docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-provider-js-updated'

      - name: Sync example_consumer_python docs
        run: bundle exec scripts/sync/example_consumer_python.rb && echo 'COMMIT_MESSAGE="synced example_consumer_python docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-consumer-python-updated'

      - name: Sync example_provider_python docs
        run: bundle exec scripts/sync/example_provider_python.rb && echo 'COMMIT_MESSAGE="synced example_provider_python docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-provider-python-updated'

      - name: Sync pact-js-workshop docs
        run: bundle exec scripts/sync/introduction_workshop.rb && echo 'COMMIT_MESSAGE="synced introduction_workshop docs"' >> $GITHUB_ENV
        if: github.event.action == 'pact-workshop-js-updated'

      - name: Sync example_consumer_js_sns docs
        run: bundle exec scripts/sync/example_consumer_js_sns.rb && echo 'COMMIT_MESSAGE="synced example_consumer_js_sns docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-consumer-js-sns-updated'

      - name: Sync example_provider_js_sns docs
        run: bundle exec scripts/sync/example_provider_js_sns.rb && echo 'COMMIT_MESSAGE="synced example_provider_js_sns docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-provider-js-sns-updated'

      - name: Sync example_consumer_golang docs
        run: bundle exec scripts/sync/example_consumer_golang.rb && echo 'COMMIT_MESSAGE="synced example_consumer_golang docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-consumer-golang-updated'

      - name: Sync example_provider_golang docs
        run: bundle exec scripts/sync/example_provider_golang.rb && echo 'COMMIT_MESSAGE="synced example_provider_golang docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-provider-golang-updated'

      - name: Sync example_provider_bidirectional_dredd docs
        run: bundle exec scripts/sync/example_provider_bidirectional_dredd.rb && echo 'COMMIT_MESSAGE="synced example_provider_bidirectional_dredd docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-provider-dredd-updated'

      - name: Sync example_provider_bidirectional_postman docs
        run: bundle exec scripts/sync/example_provider_bidirectional_postman.rb && echo 'COMMIT_MESSAGE="synced example_provider_bidirectional_postman docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-provider-postman-updated'

      - name: Sync example_provider_bidirectional_restassured docs
        run: bundle exec scripts/sync/example_provider_bidirectional_restassured.rb && echo 'COMMIT_MESSAGE="synced example_provider_bidirectional_restassured docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-provider-restassured-updated'

      - name: Sync example_consumer_bidirectional_wiremock docs
        run: bundle exec scripts/sync/example_consumer_bidirectional_wiremock.rb && echo 'COMMIT_MESSAGE="synced example_consumer_bidirectional_wiremock docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-consumer-wiremock-updated'

      - name: Sync example_provider_bidirectional_dotnet docs
        run: bundle exec scripts/sync/example_provider_bidirectional_dotnet.rb && echo 'COMMIT_MESSAGE="synced example_provider_bidirectional_dotnet docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-bdc-provider-dotnet-updated'

      - name: Sync example_consumer_bidirectional_dotnet docs
        run: bundle exec scripts/sync/example_consumer_bidirectional_dotnet.rb && echo 'COMMIT_MESSAGE="synced example_consumer_bidirectional_dotnet docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-bdc-consumer-dotnet-updated'

      - name: Sync example_consumer_bidirectional_cypress docs
        run: bundle exec scripts/sync/example_consumer_bidirectional_cypress.rb && echo 'COMMIT_MESSAGE="synced example_consumer_bidirectional_cypress docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-bdc-consumer-cypress-updated'

      - name: Sync example_consumer_bidirectional_mountebank docs
        run: bundle exec scripts/sync/example_consumer_bidirectional_mountebank.rb && echo 'COMMIT_MESSAGE="synced example_consumer_bidirectional_mountebank docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-bdc-consumer-mountebank-updated'

      - name: Sync example_consumer_bidirectional_msw docs
        run: bundle exec scripts/sync/example_consumer_bidirectional_msw.rb && echo 'COMMIT_MESSAGE="synced example_consumer_bidirectional_msw docs"' >> $GITHUB_ENV
        if: github.event.action == 'pactflow-example-consumer-msw-js-updated'

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v4
        with:
          add: "website"
          author_name: Github Action
          author_email: docs@pact.io
          message: "chore: ${{ env.COMMIT_MESSAGE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
